prioritaires:
  - vous . propriétaire . statut
  - logement . propriétaire occupant
  - logement . résidence principale propriétaire
  - logement . résidence principale locataire
  - logement . type
  - logement . surface
  - logement . période de construction
  - ménage . personnes
  - ménage . commune
  - ménage . revenu
  - DPE . actuel
  - logement . commune
  - parcours d'aide
  # Le reste est non-linéaire, en fonction du choix
non prioritaires:
  -

situation:
  simulation . mode: "'max'"
